Feat/hybrid gateway
OrigamiTeam/saleor pull request #2
Opened 2021-03-01 13:54 UTC by BerNarDoMelow

I want to merge this change because...

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

2021-03-01 15:27 UTC, rogerql requested changes
Investigations

2021-03-01 15:27 UTC, rogerql commented on saleor/graphql/account/mutations/jwt.py
> +        print("hereeee")
remover

2021-03-01 15:27 UTC, rogerql commented on saleor/payment/gateways/hybrid/plugin.py
> +        if process_monchique_result.is_success:
como o refund é um tratamento de erro, melhor testá-lo (inverter o if) e deixar o caminho do final feliz para o fim da função

2021-03-01 15:27 UTC, rogerql commented on saleor/payment/models.py
> +    transaction_id = models.UUIDField(primary_key=False, default=None, editable=True, null=True)
vale fazer uns testes com editable=False?

2021-03-01 15:27 UTC, rogerql commented on saleor/payment/migrations/0023_monchiquepayment.py
> +                ('transaction_id', models.UUIDField(default=None, null=True)),
permite NULL por conta da autorização?

2021-03-01 16:24 UTC, BerNarDoMelow commented on saleor/payment/gateways/hybrid/plugin.py
> +        if process_monchique_result.is_success:
Isto é referente ao process e não ao refund

2021-03-01 16:29 UTC, rogerql commented on saleor/payment/gateways/hybrid/plugin.py
> +        if process_monchique_result.is_success:
não digo em termos operacionais, mais uma questão idiomática:

func():
operação A
operação B

if operação B falhou
  retorna tratando o erro
  
retorna ultima operação C

2021-03-01 16:44 UTC, BerNarDoMelow commented on saleor/payment/gateways/hybrid/plugin.py
> +        if process_monchique_result.is_success:
Ok sim entendi!

2021-03-05 16:07 UTC, rogerql requested changes
just swap refund order

2021-03-05 16:07 UTC, rogerql commented on saleor/payment/gateways/hybrid/plugin.py
> +        refund_monchique_result = MyMonchiqueGatewayPlugin.refund_payment(self, payment_information, previous_value)
Refund Adyen first which is the more important

2021-03-05 16:08 UTC, BerNarDoMelow commented on saleor/payment/gateways/hybrid/plugin.py
> +        refund_monchique_result = MyMonchiqueGatewayPlugin.refund_payment(self, payment_information, previous_value)
true

2021-03-05 17:31 UTC, rogerql approved these changes

2021-03-05 17:31 UTC, merged